# Generated by Django 5.1.7 on 2025-03-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_field',
            new_name='author',
        ),
    ]
